# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 895a521f86934f4fdd9d20e6bff5db15d45953997e57578d183df0930bf56ea1a6a63e0d3f73eef7fbf81f0ff6f8a623e386d3dd581e2d3fde659b83975d296c
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_associates_tag: <%= ENV["AWS_ASSOCIATES_TAG"] %>

test:
  secret_key_base: 7b4c659a6b15cc0a5e4e7aa021b0135ce567905b05f8f13f9c939cf67e04b1dc4c94217f304148272a60d7458842ef5bece5e75ff786ffead40e0a578393817b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  aws_associates_tag: <%= ENV["AWS_ASSOCIATES_TAG"] %>